services:
  zambia-app-dev:
    image: node:lts-slim
    container_name: zambia_development_app
    working_dir: /app
    ports:
      - '4200:4200'
    volumes:
      - .:/app
      - node_modules:/app/node_modules
    command: >
      bash -c "
        npm ci && 
        npm install --no-save cross-env &&
        npm run config:dev &&
        npx nx run zambia:serve:development --host=0.0.0.0 --poll=500
      "
    environment:
      - NODE_ENV=development
      - HOST=0.0.0.0
    env_file:
      - .env
      - .env.development

volumes:
  node_modules:
