name: CI

on:
  push:
    branches:
      - master
  pull_request:

permissions:
  actions: read
  contents: read

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      # Cache node_modules
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'

      - run: npm ci --legacy-peer-deps
      - run: npx playwright install --with-deps

      # Use a simpler approach that doesn't rely on Nx Cloud
      - name: Get Affected Projects
        run: |
          if [ "${{ github.event_name }}" = "pull_request" ]; then
            echo "BASE_SHA=$(git merge-base origin/${{ github.base_ref }} HEAD)" >> $GITHUB_ENV
            echo "Running against PR base"
          else
            echo "BASE_SHA=$(git rev-parse HEAD~1)" >> $GITHUB_ENV
            echo "Running against previous commit"
          fi

      # Run nx affected commands without cloud dependencies
      - name: Lint, Format and Build
        run: npx nx affected --base=${{ env.BASE_SHA }} --head=HEAD -t lint format build build-storybook
